source 'http://rubygems.org'

# openstudio-standards is HUGE because of many very very large test files etc
gem 'openstudio-standards', github: 'nrel/openstudio-standards', branch: 'master'
gem 'openstudio-workflow', github: 'nrel/openstudio-workflow-gem', branch: 'develop'
