# frozen_string_literal: true

source 'http://rubygems.org'

# openstudio-standards is HUGE because of many very very large test files etc
# gem 'openstudio-standards', github: 'nrel/openstudio-standards', tag: 'v0.2.11'
gem 'openstudio-workflow', github: 'nrel/openstudio-workflow-gem', tag: 'v2.2.0'
