
function main()
{
    startApplication("SketchUp");
    snooze(3.0);
    mouseClick(waitForObjectItem(":Untitled - SketchUp Pro_MenuBar", "File"));
    snooze(3.0);
    mouseClick(waitForObjectItem(":File_MenuItem", "Open..."));
    snooze(2.0);
    type(":Open_Edit", "c:\\OpenStudio_Squish_SVN\\squish\\SquishTestingResources\\5x5grid.skp");
    snooze(3.0);
    type(":Open_Edit", "<Return>");
    snooze(3.0);
    type(":5x5grid.skp - SketchUp Pro_WindowsControl", "c");
    snooze(2.0);
    mouseClick(":5x5grid.skp - SketchUp Pro_WindowsControl", 616, 408, MouseButton.LeftButton);
    snooze(3.0);
    type(":5x5grid.skp - SketchUp Pro_WindowsControl", "`");
    mouseClick(waitForObject(":21940_ToolbarItem"));
    mouseClick(waitForObject(":5x5grid.skp - SketchUp Pro_WindowsControl"), 554, 693, MouseButton.LeftButton);
    type(waitForObject(":Place 3D Text_Edit"), "hellp");
    type(waitForObject(":Place 3D Text_Edit"), "<Return>");
    type(waitForObject(":Place 3D Text_Edit"), "<Backspace>");
    type(waitForObject(":Place 3D Text_Edit"), "<Backspace>");
    type(waitForObject(":Place 3D Text_Edit"), "o");
    clickButton(waitForObject(":Place 3D Text.Place_Button"));
    mouseClick(waitForObject(":5x5grid.skp - SketchUp Pro_WindowsControl"), 538, 803, MouseButton.LeftButton);
    snooze(2.0);
    mouseClick(":50025_ToolbarItem_2");
    snooze(2.0);
    mouseClick(":5x5grid.skp - SketchUp Pro_WindowsControl", 780, 468, MouseButton.LeftButton);
    snooze(3.0);
    mouseClick(waitForObjectItem(":5x5grid.skp - SketchUp Pro_MenuBar", "Edit"));
    snooze(2.0);
    mouseClick(waitForObjectItem(":Edit_MenuItem_2", "Component (1 in model)"));
    snooze(1.0);
    mouseClick(waitForObjectItem(":Edit.Component (1 in model)_MenuItem_2", "Edit Component"));
    snooze(2.0);
    mouseClick(":5x5grid.skp - SketchUp Pro_WindowsControl", 887, 429, MouseButton.LeftButton);
    snooze(2.0);
    mouseClick(":21048_ToolbarItem_2");
    snooze(2.0);
    mouseClick(":5x5grid.skp - SketchUp Pro_WindowsControl", 618, 410, MouseButton.LeftButton);
    snooze(1.0);
    mouseClick(":5x5grid.skp - SketchUp Pro_WindowsControl", 783, 464, MouseButton.LeftButton);
    snooze(2.0);
    mouseClick(":5x5grid.skp - SketchUp Pro_WindowsControl", 782, 466, MouseButton.LeftButton);
    snooze(1.0);
    mouseClick(":5x5grid.skp - SketchUp Pro_WindowsControl", 868, 343, MouseButton.LeftButton);
    snooze(3.0);
    mouseClick(waitForObjectItem(":5x5grid.skp - SketchUp Pro_MenuBar", "Plugins"));
    snooze(1.0);
    mouseClick(waitForObjectItem(":Plugins_MenuItem_2", "OpenStudio"));
    snooze(3.0);
    mouseClick(waitForObjectItem(":Plugins.OpenStudio_MenuItem_2", "Object Info"));
    snooze(3.0);
    mouseClick(":21022_ToolbarItem");
    snooze(2.0);
    type(":5x5grid.skp - SketchUp Pro_WindowsControl", "<Escape>");
    mouseClick(":5x5grid.skp - SketchUp Pro_WindowsControl", 781, 398, MouseButton.LeftButton);
    test.vp("VP5");
    mouseClick(":Object Info_Dialog", 589, 23, MouseButton.LeftButton);
}
