# Most of the maintainers of this code are professional engineers,
# not professional Rubyists.  The style guide for this project
# has been modified accordingly, with explanations given below.
# Where a Cop is not listed, it uses the Rubocop defaults.

AllCops:
  Exclude:
    - 'doc/**/*'
    - 'gemfiles/**/gems/**/*'
    - 'measures/**/*'
    - 'python/**/*'
    - 'test/**/*'
    - 'update_eplus_compare/**/*'
    - 'weatherdata/**/*'

inherit_from:
  - http://s3.amazonaws.com/openstudio-resources/styles/rubocop.yml

# =============== OpenStudio Resources Specific ===========
