# Most of the maintainers of this code are professional engineers,
# not professional Rubyists.  The style guide for this project
# has been modified accordingly, with explanations given below.
# Where a Cop is not listed, it uses the Rubocop defaults.

AllCops:
  NewCops: enable
  Exclude:
    - 'doc/**/*'
    - 'gemfiles/**/gems/**/*'
    - 'measures/**/*'
    - 'python/**/*'
    - 'test/**/*'
    - 'update_eplus_compare/**/*'
    - 'weatherdata/**/*'
    - 'model/refbuildingtests/measures/**/*'

inherit_from:
  - http://s3.amazonaws.com/openstudio-resources/styles/rubocop.yml

# =============== OpenStudio Resources Specific ===========

# Allow long lines to encourage sufficiently
# detailed user-facing log messages.
Layout/LineLength:
  Max: 1200
  Severity: warning

Layout/TrailingWhitespace:
  Enabled: true

# Do not enforce snake_case
Naming/VariableName:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

# I like to use _var for an Optional thing
Lint/UnderscorePrefixedVariableName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
