name: openstudio-resources
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - df2gspread
  - docopt
  - lxml
  - ipywidgets
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - requests
  - seaborn
  - tqdm
  - xmldiff
