import openstudio

from lib.baseline_model import BaselineModel

model = BaselineModel()

# make a 2 story, 100m X 50m, 3 zone core building
model.add_geometry(length=100, width=50, num_floors=2, floor_to_floor_height=4, plenum_height=0, perimeter_zone_depth=0)

# add windows at a 40% window-to-wall ratio
model.add_windows(wwr=0.4, offset=1, application_type="Above Floor")

# add thermostats
model.add_thermostats(heating_setpoint=24, cooling_setpoint=28)

# assign constructions from a local library to the walls/windows/etc. in the model
model.set_constructions()

# set whole building space type; simplified 90.1-2004 Large Office Whole Building
model.set_space_type()

# add design days to the model (Chicago)
model.add_design_days()

# add ASHRAE System type 03, PSZ-AC
model.add_hvac(ashrae_sys_num="03")

air_systems = model.getAirLoopHVACs()

for i, s in enumerate(air_systems):
    if i == 0:
        hx_performance = openstudio.model.HeatExchangerDesiccantBalancedFlowPerformanceDataType1(model)
        hx_performance.autosizeNominalAirFlowRate()
        hx_performance.autosizeNominalAirFaceVelocity()
        hx_performance.setNominalElectricPower(0)
        hx_performance.setTemperatureEquationCoefficient1(-7.18302e00)
        hx_performance.setTemperatureEquationCoefficient2(-1.84967e02)
        hx_performance.setTemperatureEquationCoefficient3(1.00051e00)
        hx_performance.setTemperatureEquationCoefficient4(1.16033e04)
        hx_performance.setTemperatureEquationCoefficient5(-5.07550e01)
        hx_performance.setTemperatureEquationCoefficient6(-1.68467e-02)
        hx_performance.setTemperatureEquationCoefficient7(5.82213e01)
        hx_performance.setTemperatureEquationCoefficient8(5.98863e-01)
        hx_performance.setMinimumRegenerationInletAirHumidityRatioforTemperatureEquation(0.007143)
        hx_performance.setMaximumRegenerationInletAirHumidityRatioforTemperatureEquation(0.024286)
        hx_performance.setMinimumRegenerationInletAirTemperatureforTemperatureEquation(17.83333)
        hx_performance.setMaximumRegenerationInletAirTemperatureforTemperatureEquation(48.88889)
        hx_performance.setMinimumProcessInletAirHumidityRatioforTemperatureEquation(0.005000)
        hx_performance.setMaximumProcessInletAirHumidityRatioforTemperatureEquation(0.015714)
        hx_performance.setMinimumProcessInletAirTemperatureforTemperatureEquation(4.583333)
        hx_performance.setMaximumProcessInletAirTemperatureforTemperatureEquation(21.83333)
        hx_performance.setMinimumRegenerationAirVelocityforTemperatureEquation(2.286)
        hx_performance.setMaximumRegenerationAirVelocityforTemperatureEquation(4.826)
        hx_performance.setMinimumRegenerationOutletAirTemperatureforTemperatureEquation(16.66667)
        hx_performance.setMaximumRegenerationOutletAirTemperatureforTemperatureEquation(46.11111)
        hx_performance.setMinimumRegenerationInletAirRelativeHumidityforTemperatureEquation(10.0)
        hx_performance.setMaximumRegenerationInletAirRelativeHumidityforTemperatureEquation(100.0)
        hx_performance.setMinimumProcessInletAirRelativeHumidityforTemperatureEquation(80.0)
        hx_performance.setMaximumProcessInletAirRelativeHumidityforTemperatureEquation(100.0)
        hx_performance.setHumidityRatioEquationCoefficient1(3.13878e-03)
        hx_performance.setHumidityRatioEquationCoefficient2(1.09689e00)
        hx_performance.setHumidityRatioEquationCoefficient3(-2.63341e-05)
        hx_performance.setHumidityRatioEquationCoefficient4(-6.33885e00)
        hx_performance.setHumidityRatioEquationCoefficient5(9.38196e-03)
        hx_performance.setHumidityRatioEquationCoefficient6(5.21186e-05)
        hx_performance.setHumidityRatioEquationCoefficient7(6.70354e-02)
        hx_performance.setHumidityRatioEquationCoefficient8(-1.60823e-04)
        hx_performance.setMinimumRegenerationInletAirHumidityRatioforHumidityRatioEquation(0.007143)
        hx_performance.setMaximumRegenerationInletAirHumidityRatioforHumidityRatioEquation(0.024286)
        hx_performance.setMinimumRegenerationInletAirTemperatureforHumidityRatioEquation(17.83333)
        hx_performance.setMaximumRegenerationInletAirTemperatureforHumidityRatioEquation(48.88889)
        hx_performance.setMinimumProcessInletAirHumidityRatioforHumidityRatioEquation(0.005000)
        hx_performance.setMaximumProcessInletAirHumidityRatioforHumidityRatioEquation(0.015714)
        hx_performance.setMinimumProcessInletAirTemperatureforHumidityRatioEquation(4.583333)
        hx_performance.setMaximumProcessInletAirTemperatureforHumidityRatioEquation(21.83333)
        hx_performance.setMinimumRegenerationAirVelocityforHumidityRatioEquation(2.286)
        hx_performance.setMaximumRegenerationAirVelocityforHumidityRatioEquation(4.826)
        hx_performance.setMinimumRegenerationOutletAirHumidityRatioforHumidityRatioEquation(0.007811)
        hx_performance.setMaximumRegenerationOutletAirHumidityRatioforHumidityRatioEquation(0.026707)
        hx_performance.setMinimumRegenerationInletAirRelativeHumidityforHumidityRatioEquation(10.0)
        hx_performance.setMaximumRegenerationInletAirRelativeHumidityforHumidityRatioEquation(100.0)
        hx_performance.setMinimumProcessInletAirRelativeHumidityforHumidityRatioEquation(80.0)
        hx_performance.setMaximumProcessInletAirRelativeHumidityforHumidityRatioEquation(100.0)
        hx = openstudio.model.HeatExchangerDesiccantBalancedFlow(model, hx_performance)
        availability_schedule = openstudio.model.ScheduleConstant(model)
        availability_schedule.setValue(0.5)
        hx.setAvailabilitySchedule(availability_schedule)
        hx.setEconomizerLockout(False)
    elif i == 1:  # try convenience ctor:
        hx = openstudio.model.HeatExchangerDesiccantBalancedFlow(model)
        availability_schedule = openstudio.model.ScheduleConstant(model)
        availability_schedule.setValue(0.75)
        hx.setAvailabilitySchedule(availability_schedule)
        hx.setEconomizerLockout(True)
        hx_performance = openstudio.model.HeatExchangerDesiccantBalancedFlowPerformanceDataType1(model)
        hx_performance.setNominalAirFlowRate(1.0)
        hx_performance.setNominalAirFaceVelocity(2.0)
        hx_performance.setNominalElectricPower(0)
        hx_performance.setTemperatureEquationCoefficient1(-7.18302e00)
        hx_performance.setTemperatureEquationCoefficient2(-1.84967e02)
        hx_performance.setTemperatureEquationCoefficient3(1.00051e00)
        hx_performance.setTemperatureEquationCoefficient4(1.16033e04)
        hx_performance.setTemperatureEquationCoefficient5(-5.07550e01)
        hx_performance.setTemperatureEquationCoefficient6(-1.68467e-02)
        hx_performance.setTemperatureEquationCoefficient7(5.82213e01)
        hx_performance.setTemperatureEquationCoefficient8(5.98863e-01)
        hx_performance.setMinimumRegenerationInletAirHumidityRatioforTemperatureEquation(0.007143)
        hx_performance.setMaximumRegenerationInletAirHumidityRatioforTemperatureEquation(0.024286)
        hx_performance.setMinimumRegenerationInletAirTemperatureforTemperatureEquation(17.83333)
        hx_performance.setMaximumRegenerationInletAirTemperatureforTemperatureEquation(48.88889)
        hx_performance.setMinimumProcessInletAirHumidityRatioforTemperatureEquation(0.005000)
        hx_performance.setMaximumProcessInletAirHumidityRatioforTemperatureEquation(0.015714)
        hx_performance.setMinimumProcessInletAirTemperatureforTemperatureEquation(4.583333)
        hx_performance.setMaximumProcessInletAirTemperatureforTemperatureEquation(21.83333)
        hx_performance.setMinimumRegenerationAirVelocityforTemperatureEquation(2.286)
        hx_performance.setMaximumRegenerationAirVelocityforTemperatureEquation(4.826)
        hx_performance.setMinimumRegenerationOutletAirTemperatureforTemperatureEquation(16.66667)
        hx_performance.setMaximumRegenerationOutletAirTemperatureforTemperatureEquation(46.11111)
        hx_performance.setMinimumRegenerationInletAirRelativeHumidityforTemperatureEquation(10.0)
        hx_performance.setMaximumRegenerationInletAirRelativeHumidityforTemperatureEquation(100.0)
        hx_performance.setMinimumProcessInletAirRelativeHumidityforTemperatureEquation(80.0)
        hx_performance.setMaximumProcessInletAirRelativeHumidityforTemperatureEquation(100.0)
        hx_performance.setHumidityRatioEquationCoefficient1(3.13878e-03)
        hx_performance.setHumidityRatioEquationCoefficient2(1.09689e00)
        hx_performance.setHumidityRatioEquationCoefficient3(-2.63341e-05)
        hx_performance.setHumidityRatioEquationCoefficient4(-6.33885e00)
        hx_performance.setHumidityRatioEquationCoefficient5(9.38196e-03)
        hx_performance.setHumidityRatioEquationCoefficient6(5.21186e-05)
        hx_performance.setHumidityRatioEquationCoefficient7(6.70354e-02)
        hx_performance.setHumidityRatioEquationCoefficient8(-1.60823e-04)
        hx_performance.setMinimumRegenerationInletAirHumidityRatioforHumidityRatioEquation(0.007143)
        hx_performance.setMaximumRegenerationInletAirHumidityRatioforHumidityRatioEquation(0.024286)
        hx_performance.setMinimumRegenerationInletAirTemperatureforHumidityRatioEquation(17.83333)
        hx_performance.setMaximumRegenerationInletAirTemperatureforHumidityRatioEquation(48.88889)
        hx_performance.setMinimumProcessInletAirHumidityRatioforHumidityRatioEquation(0.005000)
        hx_performance.setMaximumProcessInletAirHumidityRatioforHumidityRatioEquation(0.015714)
        hx_performance.setMinimumProcessInletAirTemperatureforHumidityRatioEquation(4.583333)
        hx_performance.setMaximumProcessInletAirTemperatureforHumidityRatioEquation(21.83333)
        hx_performance.setMinimumRegenerationAirVelocityforHumidityRatioEquation(2.286)
        hx_performance.setMaximumRegenerationAirVelocityforHumidityRatioEquation(4.826)
        hx_performance.setMinimumRegenerationOutletAirHumidityRatioforHumidityRatioEquation(0.007811)
        hx_performance.setMaximumRegenerationOutletAirHumidityRatioforHumidityRatioEquation(0.026707)
        hx_performance.setMinimumRegenerationInletAirRelativeHumidityforHumidityRatioEquation(10.0)
        hx_performance.setMaximumRegenerationInletAirRelativeHumidityforHumidityRatioEquation(100.0)
        hx_performance.setMinimumProcessInletAirRelativeHumidityforHumidityRatioEquation(80.0)
        hx_performance.setMaximumProcessInletAirRelativeHumidityforHumidityRatioEquation(100.0)
        hx.setHeatExchangerPerformance(hx_performance)

    oa_system = s.airLoopHVACOutdoorAirSystem().get()
    oa_node = oa_system.outboardOANode().get()
    hx.addToNode(oa_node)

    spm_oa_pretreat = openstudio.model.SetpointManagerOutdoorAirPretreat(model)
    spm_oa_pretreat.setMinimumSetpointTemperature(-99.0)
    spm_oa_pretreat.setMaximumSetpointTemperature(99.0)
    spm_oa_pretreat.setMinimumSetpointHumidityRatio(0.00001)
    spm_oa_pretreat.setMaximumSetpointHumidityRatio(1.0)
    mixed_air_node = oa_system.mixedAirmodelObject().get().to_Node().get()
    spm_oa_pretreat.setReferenceSetpointNode(mixed_air_node)
    spm_oa_pretreat.setMixedAirStreamNode(mixed_air_node)
    spm_oa_pretreat.setOutdoorAirStreamNode(oa_system.outboardOANode().get())
    return_air_node = oa_system.returnAirmodelObject().get().to_Node().get()
    spm_oa_pretreat.setReturnAirStreamNode(return_air_node)
    hx_outlet = hx.primaryAirOutletmodelObject().get().to_Node().get()
    spm_oa_pretreat.addToNode(hx_outlet)


# save the OpenStudio model (.osm)
model.save_openstudio_osm(osm_save_directory=None, osm_name="in.osm")
