name: Test OS SDK Installer - Full Suite

on:
  workflow_dispatch:
    inputs:
      os_installer_ubuntu_1804:
        description: 'The Link where to download the Ubuntu 1804 OpenStudio SDK Installer (.deb)'
        required: true
        default: 'https://github.com/NREL/OpenStudio/releases/download/v3.2.1/OpenStudio-3.2.1%2Bbdbdbc9da6-Ubuntu-18.04.deb'
      os_installer_ubuntu_2004:
        description: 'The Link where to download the Ubuntu 2004 OpenStudio SDK Installer (.deb)'
        required: true
        default: 'https://github.com/NREL/OpenStudio/releases/download/v3.2.1/OpenStudio-3.2.1%2Bbdbdbc9da6-Ubuntu-20.04.deb'
    os_installer_windows:
        description: 'The Link where to download the Windows OpenStudio SDK Installer (.exe)'
        required: true
        default: 'https://github.com/NREL/OpenStudio/releases/download/v3.2.1/OpenStudio-3.2.1%2Bbdbdbc9da6-Windows.exe'
    os_installer_osx:
        description: 'The Link where to download the Mac OSX Installer (.dmg)'
        required: true
        default: 'https://github.com/NREL/OpenStudio/releases/download/v3.2.1/OpenStudio-3.2.1%2Bbdbdbc9da6-Darwin.dmg'

jobs:
  installer_ubuntu_1804:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Download and install OS SDK installer
      shell: bash
      run: |
        set -x
        echo "Installer link: ${{ github.event.inputs.os_installer_ubuntu_1804 }}"
        sudo apt update
        wget '${{ github.event.inputs.os_installer_ubuntu_1804 }}'
        sudo apt install -y ./OpenStudio*.deb
        openstudio openstudio_version

    - name: Setup python deps
      shell: bash
      run: |
        pip install -r requirements.txt

   # - name: Run model_tests.rb
   #   shell: bash
   #   run: |
   #     set -x
   #     echo "nproc=$(nproc)"
   #     N=$(nproc) CUSTOMTAG=SHA openstudio model_tests.rb

    - name: Run highlevel_tests
      if: always()
      shell: bash
      run: |
        set -x
        MT_CPU=$(nproc) openstudio highlevel_tests.rb

    - name: Generate HTML and heatmap
      if: ${{ always() }}
      shell: bash
      run: |
        set -x
        python process_results.py test-status --quiet || true
        python process_results.py heatmap --quiet || true

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name: Test-Results
          path: Test-Stability/*

  installer_ubuntu_2004:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Download and install OS SDK installer
      shell: bash
      run: |
        set -x
        echo "Installer link: ${{ github.event.inputs.os_installer_ubuntu_2004 }}"
        sudo apt update
        wget '${{ github.event.inputs.os_installer_ubuntu_2004 }}'
        sudo apt install -y ./OpenStudio*.deb
        openstudio openstudio_version

    - name: Setup python deps
      shell: bash
      run: |
        pip install -r requirements.txt

   # - name: Run model_tests.rb
   #   shell: bash
   #   run: |
   #     set -x
   #     echo "nproc=$(nproc)"
   #     N=$(nproc) CUSTOMTAG=SHA openstudio model_tests.rb

    - name: Run highlevel_tests
      if: always()
      shell: bash
      run: |
        set -x
        MT_CPU=$(nproc) openstudio highlevel_tests.rb

    - name: Generate HTML and heatmap
      if: ${{ always() }}
      shell: bash
      run: |
        set -x
        python process_results.py test-status --quiet || true
        python process_results.py heatmap --quiet || true

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name: Test-Results
          path: Test-Stability/*


  installer_ubuntu_2004:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Download and install OS SDK installer
      shell: bash
      run: |
        set -x
        echo "Installer link: ${{ github.event.inputs.os_installer_ubuntu_2004 }}"
        sudo apt update
        wget '${{ github.event.inputs.os_installer_ubuntu_2004 }}'
        sudo apt install -y ./OpenStudio*.deb
        openstudio openstudio_version

    - name: Setup python deps
      shell: bash
      run: |
        pip install -r requirements.txt

   # - name: Run model_tests.rb
   #   shell: bash
   #   run: |
   #     set -x
   #     echo "nproc=$(nproc)"
   #     N=$(nproc) CUSTOMTAG=SHA openstudio model_tests.rb

    - name: Run highlevel_tests
      if: always()
      shell: bash
      run: |
        set -x
        MT_CPU=$(nproc) openstudio highlevel_tests.rb

    - name: Generate HTML and heatmap
      if: ${{ always() }}
      shell: bash
      run: |
        set -x
        python process_results.py test-status --quiet || true
        python process_results.py heatmap --quiet || true

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name: Test-Results
          path: Test-Stability/*

  installer_windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Download and install OS SDK installer
      shell: bash
      run: |
        set -x
        echo "Installer link: ${{ github.event.inputs.os_installer_windows }}"
        wget '${{ github.event.inputs.os_installer_windows }}'
        # script installs to /c/openstudio
        ${{ github.event.inputs.os_installer_windows }} --script ci/install-windows.qs
        /c/openstudio/bin/openstudio.exe openstudio_version

    - name: Setup python deps
      shell: bash
      run: |
        pip install -r requirements.txt

   # - name: Run model_tests.rb
   #   shell: bash
   #   run: |
   #     set -x
   #     echo "nproc=$(nproc)"
   #     N=$(nproc) CUSTOMTAG=SHA openstudio model_tests.rb

    - name: Run highlevel_tests
      if: always()
      shell: bash
      run: |
        set -x
        MT_CPU=$(nproc) /c/openstudio/bin/openstudio.exe highlevel_tests.rb

    - name: Generate HTML and heatmap
      if: ${{ always() }}
      shell: bash
      run: |
        set -x
        python process_results.py test-status --quiet || true
        python process_results.py heatmap --quiet || true

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name: Test-Results
          path: Test-Stability/*


  installer_mac_osx:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Download and install OS SDK installer
      shell: bash
      run: |
        set -x
        echo "Installer link: ${{ github.event.inputs.os_installer_osx }}"
        wget '${{ github.event.inputs.os_installer_osx }}'
        OS_NAME=$(ls *.dmg)
        OS_NAME_NO_EXT=$(basename $OS_NAME .dmg)
        sed -i -e "s|REPLACEME|$HOME/Applications|" ci/install-mac.qs
        hdiutil attach ${OS_NAME}.dmg
        sudo /Volumes/${OS_NAME_NO_EXT}/${OS_NAME_NO_EXT}.app/Contents/MacOS/${OS_NAME_NO_EXT} --script ci/install-mac.qs
        hdiutil detach /Volumes/${OS_NAME_NO_EX} -force
        openstudio openstudio_version

    - name: Setup python deps
      shell: bash
      run: |
        pip install -r requirements.txt

   # - name: Run model_tests.rb
   #   shell: bash
   #   run: |
   #     set -x
   #     echo "nproc=$(nproc)"
   #     N=$(nproc) CUSTOMTAG=SHA openstudio model_tests.rb

    - name: Run highlevel_tests
      if: always()
      shell: bash
      run: |
        set -x
        MT_CPU=$(nproc) openstudio highlevel_tests.rb

    - name: Generate HTML and heatmap
      if: ${{ always() }}
      shell: bash
      run: |
        set -x
        python process_results.py test-status --quiet || true
        python process_results.py heatmap --quiet || true

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name: Test-Results
          path: Test-Stability/*
